In [2]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D"],
    "Age": [21, 22, 20, 23],
    "Marks": [80, 90, 75, 85]
}

df = pd.DataFrame(data)
print(df)

  Name  Age  Marks
0    A   21     80
1    B   22     90
2    C   20     75
3    D   23     85

In [3]:
df.head(2)
df.columns
df.shape
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   21.500000  82.500000
std     1.290994   6.454972
min    20.000000  75.000000
25%    20.750000  78.750000
50%    21.500000  82.500000
75%    22.250000  86.250000
max    23.000000  90.000000

In [4]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E", "F", "G"],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "IT", "Sales"],
    "Salary": [50000, 40000, 60000, 55000, 45000, 70000, 48000],
    "Age": [25, 28, 30, 35, 26, 32, 29],
    "Experience": [2, 3, 5, 7, 2, 6, 4]
}

df = pd.DataFrame(data)
df

  Name Department  Salary  Age  Experience
0    A         IT   50000   25           2
1    B         HR   40000   28           3
2    C         IT   60000   30           5
3    D      Sales   55000   35           7
4    E         HR   45000   26           2
5    F         IT   70000   32           6
6    G      Sales   48000   29           4

In [5]:
df.head(3)
df.shape
df.columns
df[['Name','Salary']]
df['Salary'].mean()
df['Age'].max()
df[df['Salary']>50_000]
df[df['Department']=='IT']
df[df['Age']<30]
df[(df['Salary']>=45_000) & (df['Salary']<=65_000)]
df.query('Department=="HR" and Experience > 2')
df[(df['Age']==25) | (df['Age']==35)]

  Name Department  Salary  Age  Experience
0    A         IT   50000   25           2
3    D      Sales   55000   35           7

In [6]:
df.assign(Bonus=df['Salary']*0.1)

  Name Department  Salary  Age  Experience   Bonus
0    A         IT   50000   25           2  5000.0
1    B         HR   40000   28           3  4000.0
2    C         IT   60000   30           5  6000.0
3    D      Sales   55000   35           7  5500.0
4    E         HR   45000   26           2  4500.0
5    F         IT   70000   32           6  7000.0
6    G      Sales   48000   29           4  4800.0

In [7]:
df['Senior']=df['Age'].apply(lambda x: 'True' if x>30 else 'False')
df1=df.copy()

In [8]:
df1['Salary']+5000
df

  Name Department  Salary  Age  Experience Senior
0    A         IT   50000   25           2  False
1    B         HR   40000   28           3  False
2    C         IT   60000   30           5  False
3    D      Sales   55000   35           7   True
4    E         HR   45000   26           2  False
5    F         IT   70000   32           6   True
6    G      Sales   48000   29           4  False

In [9]:
df['Tax']=df['Salary'].apply(lambda x:'20%' if x>60000 else '10%')
df

  Name Department  Salary  Age  Experience Senior  Tax
0    A         IT   50000   25           2  False  10%
1    B         HR   40000   28           3  False  10%
2    C         IT   60000   30           5  False  10%
3    D      Sales   55000   35           7   True  10%
4    E         HR   45000   26           2  False  10%
5    F         IT   70000   32           6   True  20%
6    G      Sales   48000   29           4  False  10%

In [10]:
df.groupby('Department')['Salary'].mean()
df.groupby('Department')['Salary'].max()
df.groupby('Department').count()
df.groupby('Department')['Experience'].mean()
df.groupby('Department')['Salary'].agg(["min","max"])

              min    max
Department
HR          40000  45000
IT          50000  70000
Sales       48000  55000

In [11]:
df.sort_values('Salary',ascending=False)
df.sort_values('Age')
df.sort_values(['Department','Salary'])

  Name Department  Salary  Age  Experience Senior  Tax
1    B         HR   40000   28           3  False  10%
4    E         HR   45000   26           2  False  10%
0    A         IT   50000   25           2  False  10%
2    C         IT   60000   30           5  False  10%
5    F         IT   70000   32           6   True  20%
6    G      Sales   48000   29           4  False  10%
3    D      Sales   55000   35           7   True  10%

In [12]:
category_map = {60000:'High',
                45000:'Medium',
                35000:'Low'
               }
df['Salary'].map(category_map)

0       NaN
1       NaN
2      High
3       NaN
4    Medium
5       NaN
6       NaN
Name: Salary, dtype: object

In [13]:
df['Experience']=df['Experience'].apply(lambda x: x+5)
df

  Name Department  Salary  Age  Experience Senior  Tax
0    A         IT   50000   25           7  False  10%
1    B         HR   40000   28           8  False  10%
2    C         IT   60000   30          10  False  10%
3    D      Sales   55000   35          12   True  10%
4    E         HR   45000   26           7  False  10%
5    F         IT   70000   32          11   True  20%
6    G      Sales   48000   29           9  False  10%

In [14]:
df['Department']=df['Department'].replace("IT","Tech")
df

  Name Department  Salary  Age  Experience Senior  Tax
0    A       Tech   50000   25           7  False  10%
1    B         HR   40000   28           8  False  10%
2    C       Tech   60000   30          10  False  10%
3    D      Sales   55000   35          12   True  10%
4    E         HR   45000   26           7  False  10%
5    F       Tech   70000   32          11   True  20%
6    G      Sales   48000   29           9  False  10%

In [31]:
df.groupby('Department')['Salary'].mean().max()

60000.0

In [36]:
avg = df['Salary'].mean()
df.query('Salary > @avg')

  Name Department  Salary  Age  Experience Senior  Tax
2    C       Tech   60000   30          10  False  10%
3    D      Sales   55000   35          12   True  10%
5    F       Tech   70000   32          11   True  20%

In [37]:
df.groupby('Department')['Age'].min()

Department
HR       26
Sales    29
Tech     25
Name: Age, dtype: int64

In [44]:
df[df['Salary'] > 50000]['Salary'].count()

np.int64(3)

In [53]:
highest=df['Salary'].max()
df[df['Salary'] < highest]['Salary'].max()

60000

In [56]:
df.groupby('Department')['Salary'].agg(["sum","mean","count"])

               sum     mean  count
Department
HR           85000  42500.0      2
Sales       103000  51500.0      2
Tech        180000  60000.0      3

In [75]:
max_sal = df.groupby('Department')['Salary'].mean()
# df.query('Salary>@max_sal')
max_sal

Department
HR       42500.0
Sales    51500.0
Tech     60000.0
Name: Salary, dtype: float64

In [10]:
#Open a file and print the content
with open("untitled.txt","r") as f:
    data = f.read()
print(data)

#Count number of words in the given file
with open("untitled.txt","r") as f:
    data = f.read()
count =1
for word in data:
    if(word==" "):
        count+=1
print(count)

abcd efh hij klmn
spoorthi
abcd efh hij klmn
spoorthi
4